import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Stack } from '@mui/material';
import SnackbarManager from '@/app/_components/SnackbarManager';
import Providers from '@/app/Providers';

const geistSans = localFont({
  src: '../public/geist-font-1.6.0/fonts/Geist/variable/Geist[wght].ttf',
  variable: '--font-geist-sans',
});

const geistMono = localFont({
  src: '../public/geist-font-1.6.0/fonts/GeistMono/variable/GeistMono[wght].ttf',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'CellphoneS clone - Generated by create next app',
  title: 'CellphoneS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <Stack sx={{ minHeight: '100vh' }}>
            {children}
            <SnackbarManager />
          </Stack>
        </Providers>
      </body>
    </html>
  );
}
