import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/app/Providers';
import Nav from '@/components/Nav';

const geistSans = localFont({
  src: '../public/geist-font-1.6.0/fonts/Geist/variable/Geist[wght].ttf',
  variable: '--font-geist-sans',
});

const geistMono = localFont({
  src: '../public/geist-font-1.6.0/fonts/GeistMono/variable/GeistMono[wght].ttf',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'CellphoneS clone - Generated by create next app',
  title: 'CellphoneS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
